apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-deployment
spec:
  selector:
    matchLabels:
      app: k8s-demo-app
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-demo-app
    spec:
      containers:
        - name: k8s-demo-container
          image: jason9722/k8s-demo:latest
          ports: 
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: k8s
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
spec:
  selector:
    app: k8s-demo-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort